### ISSUE TITLE
The CUBGAdditions crash for end of loading of Mods

### ISSUE THREAD

**Issue by Titoo8899** [JacksonPlayz/CUBGAdditions#1]
This was the crash of the load of your Mod:

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen
------------------------------------------------------------------------
And this is the other specifications:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.4-124.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  FMLPlugin (elulib-0.1.12.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  offlineskins (OfflineSkins-1.12.2-v4-core.jar)
  ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  CorePlugin (SmoothFont-1.12.2-1.16-b2.jar)
  HCASM (HammerCore-1.12.2-2.0.2.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 8/12/18 10:16 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at com.zeitheron.hammercore.client.utils.texture.ClientSkinManager.getPlayerMap(ClientSkinManager.java:36)
	at com.zeitheron.hammercore.proxy.RenderProxy_Client.renderPlayer(RenderProxy_Client.java:349)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_92_RenderProxy_Client_renderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at com.cubgdev.cubga.client.gui.utilities.FakePlayerRendering.renderPlayerModel(FakePlayerRendering.java:108)
	at com.cubgdev.cubga.client.gui.utilities.CUBGRenderHelper.renderPlayer(CUBGRenderHelper.java:452)
	at com.cubgdev.cubga.client.gui.GuiCubgMainMenu.func_73863_a(GuiCubgMainMenu.java:46)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.zeitheron.hammercore.client.utils.texture.ClientSkinManager.getPlayerMap(ClientSkinManager.java:36)
	at com.zeitheron.hammercore.proxy.RenderProxy_Client.renderPlayer(RenderProxy_Client.java:349)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_92_RenderProxy_Client_renderPlayer_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:59)
	at com.cubgdev.cubga.client.gui.utilities.FakePlayerRendering.renderPlayerModel(FakePlayerRendering.java:108)
	at com.cubgdev.cubga.client.gui.utilities.CUBGRenderHelper.renderPlayer(CUBGRenderHelper.java:452)
	at com.cubgdev.cubga.client.gui.GuiCubgMainMenu.func_73863_a(GuiCubgMainMenu.java:46)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)

-- Screen render details --
Details:
	Screen name: com.cubgdev.cubga.client.gui.GuiCubgMainMenu
	Mouse location: Scaled: (0, 239). Absolute: (0, 0)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2
Stacktrace:
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 198123528 bytes (188 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2749 65 mods loaded, 65 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version        | Source                                  | Signature                                |
	|:------ |:------------------------ |:-------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft                | 1.12.2         | minecraft.jar                           | None                                     |
	| UCHIJA | mcp                      | 9.42           | minecraft.jar                           | None                                     |
	| UCHIJA | FML                      | 8.0.99.99      | forge-1.12.2-14.23.4.2749.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                    | 14.23.4.2749   | forge-1.12.2-14.23.4.2749.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | smoothfontcore           | 1.12.2-1.15.1  | minecraft.jar                           | None                                     |
	| UCHIJA | obfuscate                | 0.2.5          | minecraft.jar                           | None                                     |
	| UCHIJA | elucore                  | 1.0            | minecraft.jar                           | None                                     |
	| UCHIJA | smoothfont               | 1.12.2-1.16-b2 | SmoothFont-1.12.2-1.16-b2.jar           | None                                     |
	| UCHIJA | securitycraft            | v1.8.6         | [1.12.x]+SecurityCraft+v1.8.6.jar       | None                                     |
	| UCHIJA | bttf                     | 0.1.7          | ABTTF-0.1.7.1.jar                       | None                                     |
	| UCHIJA | applecore                | 3.1.3          | AppleCore-mc1.12.2-3.1.3.jar            | None                                     |
	| UCHIJA | arcademod                | 2.1.4          | arcademod-2.1.4-1.12.2.jar              | None                                     |
	| UCHIJA | architecturecraft        | @VERSION@      | ArchitectureCraft-Mod-1.12.2.jar        | None                                     |
	| UCHIJA | quark                    | r1.4-124       | Quark-r1.4-124.jar                      | None                                     |
	| UCHIJA | autoreglib               | 1.3-18         | AutoRegLib-1.3-18.jar                   | None                                     |
	| UCHIJA | auto_third_person        | 1.0.0          | autothirdperson-1.0.0.jar               | None                                     |
	| UCHIJA | blockcraftery            | 0.1.3          | blockcraftery-0.1.3.jar                 | None                                     |
	| UCHIJA | chineseworkshop          | 1.2.4          | ChineseWorkshop_1.12.2-1.2.4.jar        | None                                     |
	| UCHIJA | chiselsandbits           | 14.20          | chiselsandbits-14.20.jar                | None                                     |
	| UCHIJA | costumes                 | 2.0.0          | Costumes-1.12.2.jar                     | None                                     |
	| UCHIJA | cgm                      | 0.4.3          | guns-0.4.3-1.12.2.jar                   | None                                     |
	| UCHIJA | cubga                    | 1.6.1          | CUBGAdditions-1.6.1-1.12.2.jar          | None                                     |
	| UCHIJA | customnpcs               | 1.12           | CustomNPCs_1.12.2(09jul18).jar          | None                                     |
	| UCHIJA | drugsandpills            | 1.4.0          | DAP-1.4.0.jar                           | None                                     |
	| UCHIJA | dsurround                | 3.4.9.14       | DynamicSurroundings-1.12.2-3.4.9.14.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJA | presets                  | 3.4.9.14       | DynamicSurroundings-1.12.2-3.4.9.14.jar | None                                     |
	| UCHIJA | elevatorid               | 1.3.6          | ElevatorMod-1.12.2-1.3.6.jar            | None                                     |
	| UCHIJA | fairylights              | 2.1.2          | fairylights-2.1.2-1.12.x.jar            | None                                     |
	| UCHIJA | flowingblocks            | 0.1.1          | flowingblocks-0.1.1.jar                 | None                                     |
	| UCHIJA | cfm                      | 5.5.0          | furniture-5.5.0-1.12.2.jar              | None                                     |
	| UCHIJA | vehicle                  | 0.20.0         | vehicle-0.20.0-mc1.12.2.jar             | None                                     |
	| UCHIJA | foodvehicles             | 1.2            | FoodVehicles-1.2.jar                    | None                                     |
	| UCHIJA | forgelin                 | 1.7.4          | Forgelin-1.7.4.jar                      | None                                     |
	| UCHIJA | freelook                 | 1.2.2          | FreeLook-1.2.2.jar                      | None                                     |
	| UCHIJA | gokistats                | @version@      | gokiStats-1.2.3.1.jar                   | None                                     |
	| UCHIJA | hammercore               | 2.0.2.2        | HammerCore-1.12.2-2.0.2.2.jar           | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJA | improvableskills         | 3.5.2r         | ImprovableSkills_1.12.2-3.5.2r.jar      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJA | lumpi                    | 0.6            | lumpi-1.12-0.6.jar                      | None                                     |
	| UCHIJA | malisiscore              | 1.12.2-6.4.0   | malisiscore-1.12.2-6.4.0.jar            | None                                     |
	| UCHIJA | malisisdoors             | 1.12.2-7.3.0   | malisisdoors-1.12.2-7.3.0.jar           | None                                     |
	| UCHIJA | modernlamps              | 1.0.3          | ModernLights-1.0.3_1.12.jar             | None                                     |
	| UCHIJA | mrcrayfishvehiclespawner | 1.1            | Mr_Crayfish_Vehicle_Spawner_1.1.jar     | None                                     |
	| UCHIJA | currency                 | 3.1.5          | NeverEnoughCurrency-4.0.1.jar           | None                                     |
	| UCHIJA | notenoughroofs           | 0.8.0.0        | notenoughroofs-1.12.2-0.8.0.0.jar       | None                                     |
	| UCHIJA | offlineskins             | 1.12.2-v4      | OfflineSkins-1.12.2-v4.jar              | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJA | rcroads                  | 0.2.1          | RC+Roads+0.2.1.jar                      | None                                     |
	| UCHIJA | redstonepaste            | 1.7.5          | redstonepaste-mc1.12-1.7.5.jar          | None                                     |
	| UCHIJA | rockhounding_core        | 3.15           | rockhounding_core-1.12.2-3.15.jar       | None                                     |
	| UCHIJA | gbook                    | 2.8.1          | Guidebook-1.12.2-2.8.1.jar              | None                                     |
	| UCHIJA | rockhounding_rocks       | 1.12.2-3.15    | rockhounding_rocks-1.12.2-3.15.jar      | None                                     |
	| UCHIJA | scarper                  | 1.0            | scarper-1.0.jar                         | None                                     |
	| UCHIJA | showcasemod              | 1.0            | showcasemod-1.12.2-1.0.0.0.jar          | None                                     |
	| UCHIJA | simplifiedhorses         | 1.2            | SimplifiedHorses-v1.2-1.11-1.12.2.jar   | None                                     |
	| UCHIJA | simplylight              | 0.1.0          | simplylight-0.1.0.jar                   | None                                     |
	| UCHIJA | snowplusplus             | 1.1.1          | snowplusplus-1.1.1.jar                  | None                                     |
	| UCHIJA | stackable                | 1.2.0          | stackable-1.12.2-1.2.0.jar              | None                                     |
	| UCHIJA | walljump                 | 1.12.2-1.1.6   | walljump-1.12.2-1.1.6.jar               | None                                     |
	| UCHIJA | waystones                | 4.0.54         | Waystones_1.12.2-4.0.54.jar             | None                                     |
	| UCHIJA | weaponlevels             | 2.5.0          | weaponlevels-2.5.0.jar                  | None                                     |
	| UCHIJA | wearableblocks           | 1.1a           | WearableBlocks-1.12.2-1.1a.jar          | None                                     |
	| UCHIJA | worldedit                | 6.1.8          | worldedit-forge-mc1.12-6.1.8-dist.jar   | None                                     |
	| UCHIJA | xaerominimap             | 1.15.3         | Xaeros_Minimap_1.15.3_Forge_1.12.jar    | None                                     |
	| UCHIJA | xaeroworldmap            | 1.2.5          | XaerosWorldMap_1.2.5_Forge_1.12.jar     | None                                     |
	| UCHIJA | elulib                   | 0.1.12         | elulib-0.1.12.jar                       | None                                     |
	| UCHIJA | pvj                      | 1.1.0          | ProjectVibrantJourneys-1.12.2-1.1.0.jar | None                                     |

	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.4-124.jar)
  vazkii.quark.base.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  squeek.applecore.asm.TransformerModuleHandler
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
offlineskins (OfflineSkins-1.12.2-v4-core.jar)
  lain.mods.skins.asm.ASMTransformer
ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  org.blockartistry.DynSurround.asm.Transformer
CorePlugin (SmoothFont-1.12.2-1.16-b2.jar)
  bre.smoothfont.asm.Transformer
HCASM (HammerCore-1.12.2-2.0.2.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 171 names; 271 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KYmxvY2tzIHsNCiAgICBCOkNodW5rTG9hZGVyPXRydWUNCiAgICBCOlRlc3NlcmFjdD10cnVlDQp9DQoNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KICAgIEI6Ik1vZCBCcm93c2VyIj10cnVlDQoNCiAgICAjIFJlcGxhY2UgdmFuaWxsYSBmdXJuYWNlIGFuZCBicmV3aW5nIHN0YW5kIHByb2dyZXNzIGJhcnMgdG8gdXNlIHNtb290aCByZW5kZXJpbmc/IFtkZWZhdWx0OiB0cnVlXQ0KICAgIEI6IlNtb290aCBWYW5pbGxhIEd1aXMiPXRydWUNCn0NCg0KDQpkZWJ1ZyB7DQogICAgQjpSYXl0cmFjZXI9ZmFsc2UNCiAgICBCOlphcHBlcj1mYWxzZQ0KfQ0KDQoNCml0ZW1zIHsNCiAgICBCOkFjY3VtdWxhdG9yPXRydWUNCn0NCg0KDQppd3JlbmNoIHsNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpHcmVlbj0yMkZGMjINCg0KICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpSZWQ9RkYyMjIyDQp9DQoNCg0KbmV0d29ya2luZyB7DQogICAgQjoiT2xkIE5ldHdvcmsiPXRydWUNCn0NCg0KDQoidmFuaWxsYSBpbXByb3ZlbWVudHMiIHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBmb3JjZS1zcGF3biBFbmRlciBEcmFnb24gRWdnIG9uIEVuZGVyIERyYWdvbiBkZWF0aD8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQWx3YXlzIFNwYXduIERyYWdvbiBFZ2ciPXRydWUNCn0NCg0KDQo=
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @3.5.2r

	Launched Version: 1.12.2-forge1.12.2-14.23.4.2749
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by Ocelot5836** [comment]
Please use pastebin/hastebin

**Comment by JacksonPlayz** [comment]
CUBG Additions is made specifically for our servers. Please do not use it with any other mods as we do not support crashes that have non-CUBG mods installed.

(The issue is because HammerCore and CUBG aren't compatible)

**Comment by Titoo8899** [comment]
Please make a support for Hammer Core Mod :)

**Comment by JacksonPlayz** [comment]
I won't be adding compatibility for the Hammer Core Mod. This mod is NOT intended for use in other packs except the CUBG one.
